version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ERPNumber1/ERPNumber1/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SimulationDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app-network

  sqlserver:
  # this should be the sqlserver service but i cant run it on mac
    image: mcr.microsoft.com/azure-sql-edge:latest 
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: Your_password123!
      ACCEPT_EULA: 1
      MSSQL_DB: SimulationDb
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Your_password123!' -Q 'SELECT 1' || exit 1"]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
