version: '3.8'

services:
  api:
    build:
      context: ./ERPNumber1
      dockerfile: ERPNumber1/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SimulationDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: Your_password123!
      ACCEPT_EULA: 1
      MSSQL_DB: SimulationDb
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data_backend:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Your_password123!' -C -Q 'SELECT 1' || exit 1",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - app-network

volumes:
  sqlserver_data_backend:

networks:
  app-network:
    driver: bridge
