#cloud-config
package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable --now docker
  - usermod -aG docker azureuser

  - |
    cat <<EOF > /opt/private.key.b64
    ${private_key}
    EOF
  - base64 -d /opt/private.key.b64 > /opt/private.key
  - chmod 600 /opt/private.key
  - chown azureuser:azureuser /opt/private.key
  - rm /opt/private.key.b64
  
  # - |
  #   echo "${ghcr_pat}" | docker login ghcr.io -u ${ghcr_user} --password-stdin
  # - docker pull ghcr.io/zuyd-projects/bootstrap
  # - |
  #   docker run -d \
  #   --name bootstrap-agent \
  #   -v /home/azureuser/private.key:/app/private.key:ro \
  #   -v /var/run/docker.sock:/var/run/docker.sock \
  #   -v /home/azureuser/.docker:/root/.docker:ro \
  #   -e HOSTNAME=$(hostname) \
  #   ghcr.io/zuyd-projects/bootstrap
  - curl -fsSL https://raw.githubusercontent.com/zuyd-projects/Casusgroep-1/main/infra-bootstrap-agent/install.sh | bash
