name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
    paths:
      - 'backend/**'
  pull_request:
    branches: [test]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./backend/ERPNumber1
        run: dotnet restore

      - name: Build
        working-directory: ./backend/ERPNumber1
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        working-directory: ./backend/ERPNumber1
        run: |
          dotnet test --no-build --configuration Release --verbosity normal \
            --collect:"XPlat Code Coverage" --results-directory ./TestResults \
            --logger "trx;LogFileName=test-results.trx"

  build_and_release:
    name: Build and Release Docker Image
    runs-on: ubuntu-latest
    needs: [test]
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine config file and image tag suffix
        id: config
        run: |
          if [ "${{ github.ref_name }}" = "staging" ]; then
            echo "config_file=infra/configs/backend-vm-staging.json" >> $GITHUB_OUTPUT
            echo "tag_suffix=-staging" >> $GITHUB_OUTPUT
          else
            echo "config_file=infra/configs/backend-vm.json" >> $GITHUB_OUTPUT
            echo "tag_suffix=" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/backend${{ steps.config.outputs.tag_suffix }}:$(date +'%Y%m%d%H%M%S')
          docker build -t $IMAGE_TAG ./backend
          docker push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update JSON config file with new image tags
        run: |
          CONFIG_FILE=${{ steps.config.outputs.config_file }}
          IMAGE_TAG=${{ steps.build-image.outputs.image }}

          git fetch origin config
          git checkout -B config origin/config

          cp $CONFIG_FILE $CONFIG_FILE.bak
          jq --arg backend "$IMAGE_TAG" '(.containers[] | select(.name == "backend") | .image) = $backend | .lastUpdated = (now | strftime("%Y-%m-%dT%H:%M:%SZ"))' "$CONFIG_FILE" > "$CONFIG_FILE.tmp" && mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $CONFIG_FILE

          if ! git diff --cached --quiet; then
            git commit -m "Update backend image for ${{ github.ref_name }} branch"
            git push origin HEAD:config
          else
            echo "No config changes detected."
          fi
