name: Frontend Ci/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build_and_release:
    name: Build and Release Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend Docker image
        id: build-frontend
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/frontend:$(date +'%Y%m%d%H%M%S')
          docker build -t $IMAGE_TAG --target=frontend ./frontend
          docker push $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update JSON config file with new image tags
        run: |
          CONFIG_FILE=infra/configs/frontend-vm.json
          FRONTEND_IMAGE=${{ steps.build-frontend.outputs.image }}

          git fetch origin config
          git checkout -B config origin/config

          cp $CONFIG_FILE $CONFIG_FILE.bak

          jq --arg frontend "$FRONTEND_IMAGE" '(.containers[] | select(.name == "frontend") | .image) = $frontend | .lastUpdated = (now | strftime("%Y-%m-%dT%H:%M:%SZ"))' "$CONFIG_FILE" > "$CONFIG_FILE.tmp" && mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $CONFIG_FILE

          if ! git diff --cached --quiet; then
            git commit -m "Update frontend image"
            git push origin HEAD:config
          else
            echo "No config changes detected."
          fi
